BaiTapLonWNC/Controllers/DetailBVController.cs
using BaiTapLonWNC.Models;
using BaiTapLonWNC.Models.Authen;
using Microsoft.AspNetCore.Mvc;

namespace BaiTapLonWNC.Controllers
{
    [Authen("False")]
    public class DetailBVController : Controller
    {
        private readonly BaiTapLonWebContext _context;
        public DetailBVController(BaiTapLonWebContext context)
        {
            _context = context;
        }

        public IActionResult Index(int maBV)
        {
            HttpContext.Session.SetInt32("maBV", maBV);
            var user = HttpContext.Session.GetString("UserName");
            if (user != null)
            {
                var baiViet = _context.TblBaiViets.Where(ma => ma.MaBv == maBV).FirstOrDefault();
                if (baiViet != null)
                {
                    var trangcn = _context.TblTrangCns.Where(m => m.MaTcn == baiViet.MaTcn).FirstOrDefault();
                    var like = _context.TblLikes.Where(m => m.MaBv == baiViet.MaBv).ToList();
                    var comment = _context.TblComments.Where(m => m.MaBv == baiViet.MaBv).ToList();
                    var namecn = _context.TblTrangCns.ToList();
                    var us = _context.TblUsers.Where(ma => ma.UserName.Equals(user)).FirstOrDefault();
                    var t = _context.TblTrangCns.Where(t => t.MaUs == us.MaUs).FirstOrDefault();
                    var tontai = _context.TblLikes.Where(l => l.MaTcn == t.MaTcn && l.MaBv == maBV).FirstOrDefault();
                    var detail = new Detail
                    {
                        BaiViet = baiViet,
                        TrangCn = trangcn,
                        Likes = like,
                        Comments = comment,
                        nameCn = namecn,
                        like = tontai
                    };
                    
                    return View(detail);
                }
                return RedirectToAction("Index","Home");
            }
            return RedirectToAction("Login", "Acount");
        }

        [HttpPost]
        public IActionResult like(TblLike like)
        {
            if (like.Icon != null)
            {
                
                int maBV = HttpContext.Session.GetInt32("maBV") ?? 0;
                var user = HttpContext.Session.GetString("UserName");
                if (user != null)
                {
                    var us = _context.TblUsers.Where(ma => ma.UserName.Equals(user)).FirstOrDefault();
                    if(us != null)
                    {
                        like.MaBv = maBV;
                        var t = _context.TblTrangCns.Where(t=>t.MaUs==us.MaUs).FirstOrDefault();
                        if (t != null)
                        {
                            var tontai = _context.TblLikes.Where(l => l.MaTcn == t.MaTcn && l.MaBv == maBV).FirstOrDefault();
                            if (tontai == null)
                            {
                                like.MaTcn = t.MaTcn;
                                _context.TblLikes.Add(like);
                                _context.SaveChanges();
                               
                                return RedirectToAction("Index", new { maBV = maBV });
                            }
                            else
                            {
                                _context.TblLikes.Remove(tontai);
                                _context.SaveChanges();
                                
                                return RedirectToAction("Index", new { maBV = maBV });
                            }
                        }
                    }
                }

            }
            return RedirectToAction("Index", "Home");

        }
        [HttpPost]
        public IActionResult BinhLuan(TblComment comment)
        {
            if(comment.NoiDung != null)
            {
                int maBV = HttpContext.Session.GetInt32("maBV") ?? 0;
                var user = HttpContext.Session.GetString("UserName");
                if (user != null)
                {
                    var us = _context.TblUsers.Where(ma => ma.UserName.Equals(user)).FirstOrDefault();
                    if (us != null)
                    {
                        comment.MaBv = maBV;
                        var t = _context.TblTrangCns.Where(t => t.MaUs == us.MaUs).FirstOrDefault();
                        if (t != null)
                        {
                                comment.MaTcn = t.MaTcn;
                                _context.TblComments.Add(comment);
                                _context.SaveChanges();
                                return RedirectToAction("Index", new { maBV = maBV });
                        }
                    }
                }
            }
            return RedirectToAction("Index", "Home");
        }

    }
}

BaiTapLonWNC/Controllers/TrangCNController.cs
using BaiTapLonWNC.Models;
using BaiTapLonWNC.Models.Authen;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Specialized;

namespace BaiTapLonWNC.Controllers
{
    [Authen("False")]
    public class TrangCNController : Controller
    {
        private readonly BaiTapLonWebContext _context;
        public TrangCNController(BaiTapLonWebContext context)
        {
            _context = context;
        }
        public IActionResult Index(int maTCN)
        {

            HttpContext.Session.SetInt32("maTCN", maTCN);
            if (HttpContext.Session.GetString("UserName") != null)
            {
                var trangcn = _context.TblTrangCns.Where(t => t.MaTcn == maTCN).FirstOrDefault();
                if (trangcn != null)
                {
                    var us = _context.TblUsers.Where(u => u.MaUs == trangcn.MaUs).FirstOrDefault();
                    if (us != null)
                    {
                        HttpContext.Session.SetString("UserName2", us.UserName.ToString());
                        var baiviet = _context.TblBaiViets.Where(b => b.MaTcn == trangcn.MaTcn).ToList();
                        var tcn = new TrangCaNhan
                        {
                            user = us,
                            TblTrangCn = trangcn,
                            BaiViet = baiviet
                        };
                        return View(tcn);
                    }
                }
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Login","Acount");
        }
        public IActionResult Delete(int maBV)
        {
            int maTCN = HttpContext.Session.GetInt32("maTCN") ?? 0;
            var us1 = HttpContext.Session.GetString("UserName");
            var us2 = HttpContext.Session.GetString("UserName2");
            if(us1 == us2)
            {
                var baiViet = _context.TblBaiViets.Where(b=>b.MaBv==maBV).FirstOrDefault();
                if (baiViet != null)
                {
                    _context.TblBaiViets.Remove(baiViet);
                    _context.SaveChanges();
                    HttpContext.Session.Remove("maTCN");
                    return RedirectToAction("Index", new { maTCN = maTCN });
                }

            }
            return RedirectToAction("Index", new { maTCN = maTCN });
        }
    }
}

BaiTapLonWNC/Views/DetailBV/Index.cshtml
@model BaiTapLonWNC.Models.Detail;
@using Microsoft.AspNetCore.Http;
@{
    var name = ViewContext.HttpContext.Session.GetString("Name");
}
@section Scripts{
    <script>
        $(document).ready(function () {

            $('.noidung').on('input', function () {
                var allInputsFilled = true;
                $('.noidung').each(function () {
                    if ($(this).val().trim() === '') {
                        allInputsFilled = false;
                        return false; // dừng vòng lặp nếu có một input rỗng
                    }
                });
                $('#btnComment').prop('disabled', !allInputsFilled);
            });
        });

    </script>
}
<div class="row">
    <div class="col-md-8 col__mg">
        <div class="post__detail" ></div>
        <div class="post__detail__title"><h1>@Model.BaiViet.TieuDe</h1></div>
        <div class="post__detail__user"><h3><a class="post__detail__link" asp-controller="TrangCN" asp-action="Index" asp-route-maTCN="@Model.TrangCn.MaTcn">@Model.TrangCn.NameTcn</a></h3></div>
        <div class="Post__img" style="background-image: url(/img/@Model.BaiViet.LinkAnh)"></div>
        <div class="post__detail__content">
            @Model.BaiViet.NoiDung
        </div>
        <div class="post__sl">
            <div class="post__slLike"><svg class="" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M313.4 32.9c26 5.2 42.9 30.5 37.7 56.5l-2.3 11.4c-5.3 26.7-15.1 52.1-28.8 75.2H464c26.5 0 48 21.5 48 48c0 18.5-10.5 34.6-25.9 42.6C497 275.4 504 288.9 504 304c0 23.4-16.8 42.9-38.9 47.1c4.4 7.3 6.9 15.8 6.9 24.9c0 21.3-13.9 39.4-33.1 45.6c.7 3.3 1.1 6.8 1.1 10.4c0 26.5-21.5 48-48 48H294.5c-19 0-37.5-5.6-53.3-16.1l-38.5-25.7C176 420.4 160 390.4 160 358.3V320 272 247.1c0-29.2 13.3-56.7 36-75l7.4-5.9c26.5-21.2 44.6-51 51.2-84.2l2.3-11.4c5.2-26 30.5-42.9 56.5-37.7zM32 192H96c17.7 0 32 14.3 32 32V448c0 17.7-14.3 32-32 32H32c-17.7 0-32-14.3-32-32V224c0-17.7 14.3-32 32-32z" /></svg><div>@Model.Likes.Count()</div></div>
            <div class="post__slLike"><svg class="" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M123.6 391.3c12.9-9.4 29.6-11.8 44.6-6.4c26.5 9.6 56.2 15.1 87.8 15.1c124.7 0 208-80.5 208-160s-83.3-160-208-160S48 160.5 48 240c0 32 12.4 62.8 35.7 89.2c8.6 9.7 12.8 22.5 11.8 35.5c-1.4 18.1-5.7 34.7-11.3 49.4c17-7.9 31.1-16.7 39.4-22.7zM21.2 431.9c1.8-2.7 3.5-5.4 5.1-8.1c10-16.6 19.5-38.4 21.4-62.9C17.7 326.8 0 285.1 0 240C0 125.1 114.6 32 256 32s256 93.1 256 208s-114.6 208-256 208c-37.1 0-72.3-6.4-104.1-17.9c-11.9 8.7-31.3 20.6-54.3 30.6c-15.1 6.6-32.3 12.6-50.1 16.1c-.8 .2-1.6 .3-2.4 .5c-4.4 .8-8.7 1.5-13.2 1.9c-.2 0-.5 .1-.7 .1c-5.1 .5-10.2 .8-15.3 .8c-6.5 0-12.3-3.9-14.8-9.9c-2.5-6-1.1-12.8 3.4-17.4c4.1-4.2 7.8-8.7 11.3-13.5c1.7-2.3 3.3-4.6 4.8-6.9c.1-.2 .2-.3 .3-.5z" /></svg>@Model.Comments.Count()</div>
        </div>
        <div class="post__detail__footer">
            <form asp-controller="DetailBV" asp-action="like" method="post">
                <select class="hidden" asp-for="like.Icon" hidden>
                    <option selected value="Like">like</option>
                </select>
                @if( @Model.like==null)
                {
                    <button type="submit" class =" post__detail__like custom-button"><svg class="svg__post" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M323.8 34.8c-38.2-10.9-78.1 11.2-89 49.4l-5.7 20c-3.7 13-10.4 25-19.5 35l-51.3 56.4c-8.9 9.8-8.2 25 1.6 33.9s25 8.2 33.9-1.6l51.3-56.4c14.1-15.5 24.4-34 30.1-54.1l5.7-20c3.6-12.7 16.9-20.1 29.7-16.5s20.1 16.9 16.5 29.7l-5.7 20c-5.7 19.9-14.7 38.7-26.6 55.5c-5.2 7.3-5.8 16.9-1.7 24.9s12.3 13 21.3 13L448 224c8.8 0 16 7.2 16 16c0 6.8-4.3 12.7-10.4 15c-7.4 2.8-13 9-14.9 16.7s.1 15.8 5.3 21.7c2.5 2.8 4 6.5 4 10.6c0 7.8-5.6 14.3-13 15.7c-8.2 1.6-15.1 7.3-18 15.2s-1.6 16.7 3.6 23.3c2.1 2.7 3.4 6.1 3.4 9.9c0 6.7-4.2 12.6-10.2 14.9c-11.5 4.5-17.7 16.9-14.4 28.8c.4 1.3 .6 2.8 .6 4.3c0 8.8-7.2 16-16 16H286.5c-12.6 0-25-3.7-35.5-10.7l-61.7-41.1c-11-7.4-25.9-4.4-33.3 6.7s-4.4 25.9 6.7 33.3l61.7 41.1c18.4 12.3 40 18.8 62.1 18.8H384c34.7 0 62.9-27.6 64-62c14.6-11.7 24-29.7 24-50c0-4.5-.5-8.8-1.3-13c15.4-11.7 25.3-30.2 25.3-51c0-6.5-1-12.8-2.8-18.7C504.8 273.7 512 257.7 512 240c0-35.3-28.6-64-64-64l-92.3 0c4.7-10.4 8.7-21.2 11.8-32.2l5.7-20c10.9-38.2-11.2-78.1-49.4-89zM32 192c-17.7 0-32 14.3-32 32V448c0 17.7 14.3 32 32 32H96c17.7 0 32-14.3 32-32V224c0-17.7-14.3-32-32-32H32z" /></svg></button>
                }else 
                {
                    <button type="submit" class=" post__detail__like custom-button"><svg class="svg__post" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M313.4 32.9c26 5.2 42.9 30.5 37.7 56.5l-2.3 11.4c-5.3 26.7-15.1 52.1-28.8 75.2H464c26.5 0 48 21.5 48 48c0 18.5-10.5 34.6-25.9 42.6C497 275.4 504 288.9 504 304c0 23.4-16.8 42.9-38.9 47.1c4.4 7.3 6.9 15.8 6.9 24.9c0 21.3-13.9 39.4-33.1 45.6c.7 3.3 1.1 6.8 1.1 10.4c0 26.5-21.5 48-48 48H294.5c-19 0-37.5-5.6-53.3-16.1l-38.5-25.7C176 420.4 160 390.4 160 358.3V320 272 247.1c0-29.2 13.3-56.7 36-75l7.4-5.9c26.5-21.2 44.6-51 51.2-84.2l2.3-11.4c5.2-26 30.5-42.9 56.5-37.7zM32 192H96c17.7 0 32 14.3 32 32V448c0 17.7-14.3 32-32 32H32c-17.7 0-32-14.3-32-32V224c0-17.7 14.3-32 32-32z" /></svg></button>
                }
            </form>
            <div class="post__detail__comment"><a href="#binhluan"><svg class="svg__post" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path d="M123.6 391.3c12.9-9.4 29.6-11.8 44.6-6.4c26.5 9.6 56.2 15.1 87.8 15.1c124.7 0 208-80.5 208-160s-83.3-160-208-160S48 160.5 48 240c0 32 12.4 62.8 35.7 89.2c8.6 9.7 12.8 22.5 11.8 35.5c-1.4 18.1-5.7 34.7-11.3 49.4c17-7.9 31.1-16.7 39.4-22.7zM21.2 431.9c1.8-2.7 3.5-5.4 5.1-8.1c10-16.6 19.5-38.4 21.4-62.9C17.7 326.8 0 285.1 0 240C0 125.1 114.6 32 256 32s256 93.1 256 208s-114.6 208-256 208c-37.1 0-72.3-6.4-104.1-17.9c-11.9 8.7-31.3 20.6-54.3 30.6c-15.1 6.6-32.3 12.6-50.1 16.1c-.8 .2-1.6 .3-2.4 .5c-4.4 .8-8.7 1.5-13.2 1.9c-.2 0-.5 .1-.7 .1c-5.1 .5-10.2 .8-15.3 .8c-6.5 0-12.3-3.9-14.8-9.9c-2.5-6-1.1-12.8 3.4-17.4c4.1-4.2 7.8-8.7 11.3-13.5c1.7-2.3 3.3-4.6 4.8-6.9c.1-.2 .2-.3 .3-.5z" /></svg></a></div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-8 col__mg" id="binhluan">
        @if (!string.IsNullOrEmpty(name))
        {
            <h3>@name</h3>
        }
        <form asp-controller="DetailBV" asp-action="BinhLuan" method="post">
            <div class="form-group">
                <input class="noidung" asp-for="comment.NoiDung" class="form-control" />
            </div>
            </br>
            <button id="btnComment" type="submit" class="btn btn-primary" disabled>Gửi</button>
            <span class="error" asp-validation-for="comment.NoiDung"></span>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-md-8 col__mg">
        <h3>Bình luận</h3>
        <ul class="post__comment">
            @foreach(var cm in Model.Comments){
                @foreach(var us in Model.nameCn){
                    if(cm.MaTcn==us.MaTcn){
                        <li class="post__commet__item">
                            <div class="post__item__user">
                            <h4>@us.NameTcn</h4>
                            <p>@cm.NoiDung</p>
                            </div>
                        </li>
                    }
                }
            }
        </ul>
    </div>
</div>